version: "3"
services:
    api_argos:
        build: ./api_argos
        restart: always
        environment:
            - PORT=8089
        command: uvicorn api_argos.main:app --host 0.0.0.0 --port 8089 --reload
        networks:
            - webnet

    nginx:
        image: nginx:latest
        container_name: nginx_proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/certbot:/var/www/certbot
            - ./letsencrypt:/etc/letsencrypt
        networks:
            - webnet

    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - ./letsencrypt:/etc/letsencrypt
            - ./nginx/certbot:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 1 & wait $!; done;'"
        networks:
            - webnet

networks:
    webnet:
