version: "3"
services:
    api_argos:
        build: ./
        restart: always
        ports:
            - "8089:8089"
        environment:
            - PORT=8089
        command: uvicorn api_argos.main:app --host 0.0.0.0 --port 8089 --reload
